### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated

### ISSUE THREAD

**Issue by arcdev1** [faceyspacey/redux-first-router-link#12]
Current build emits a console warning when used with React 15.5+ 

From the React docs:
> Prop types are a feature for runtime validation of props during development. We've extracted the built-in prop types to a separate package to reflect the fact that not everybody uses them. 
> 
> In 15.5, instead of accessing PropTypes from the main React object, install the prop-types package and import them from there

The affected code is at: https://github.com/faceyspacey/redux-first-router-link/blob/94a4c2f9dac775c3db21c5d1db0a35344e44770c/src/Link.js#L67

More info at:
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

Let me know if you'd like a pull request.

Redux-First-Router is a great idea by the way. Hope you keep it up.

**Comment by faceyspacey** [comment]
I actually it's the result of a package that converts flow types to react prop types:

https://github.com/brigand/babel-plugin-flow-react-proptypes/issues/104

...i looked into this quickly and i noticed they were requiring from `'prop-types'`, so at a glance i didnt know what to make of it. Being a warning, i de-prioritized it. Any clues (or even PRs) would be much appreciated and I'll get this cleaned up.

...glad u like it. Lot of time and work has been put into it. It didnt just get created this month. ...Don't forget to tweet to get the word out!

**Comment by faceyspacey** [comment]
oh...never mind. it's completely my fault. i didnt click ur link to the source before. i forgot that i was using prop types too. i hadnt touched this package in a while. i thought i relied completely on that other plugin.

**Comment by faceyspacey** [comment]
ok, the PR is building. thanks for drawing my attention to this.

https://github.com/faceyspacey/redux-first-router-link/pull/13

**Comment by arcdev1** [comment]
Wow ... thanks for the super quick turnaround. I will do my best to spread the word on Medium and Twitter.
