### ISSUE TITLE
Does not work with custom reducer location name

### ISSUE THREAD

**Issue by madaz** [faceyspacey/redux-first-router-link#19]
When overriding the state locationKey the Link does not work.

The Link src has it hard coded to `getState().location`

Supporting a nested location key would be nice e.g.  `store.getState().vendor.router`

**Comment by faceyspacey** [comment]
Link and NavLink can now can get a user-defined location key. nested location keys will have to be another time.

**Comment by faceyspacey** [comment]
update RFR + RFR-link
