### ISSUE TITLE
Link needs update for redux-first-router API change

### ISSUE THREAD

**Issue by wichert** [faceyspacey/redux-first-router-link#23]
The commit faceyspacey/redux-first-router@96bac388b5ceaa9340de355e10a3321e99cc85de changes the location key API for redux-first-router, which now causes all use of the Link component to break with this error:

```
Uncaught TypeError: (0 , _reduxFirstRouter.locationKey) is not a function
```

**Comment by faceyspacey** [comment]
@wichert thanks for bringing this to our attention. sorry about that. it's been merged and updated on NPM. thanks again @iansinnott for hooking this up so quickly.
