### ISSUE TITLE
NPM build issue

### ISSUE THREAD

**Issue by foiseworth** [faceyspacey/redux-first-router-link#25]
When I attempt to use the latest npm module I get an error: 
```js
handlePress.js?ba04:35 Uncaught TypeError: (0 , _reduxFirstRouter.getOptions) is not a function
    at exports.default (handlePress.js?ba04:35)
```
This happens because of the following code in handlePress (line 35):
```js
var _getOptions = (0, _reduxFirstRouter.getOptions)(),
        serializer = _getOptions.querySerializer;
```
Looking at the code redux-first-router doesn't have getOptions in its API and I'm unable to find the getOptions call in the handlePress code in this repo / on master (even after cloning and running the build and looking at every version of handlePress).

I'm thinking maybe the build published on  npm is an in development branch and not from master?

**Comment by faceyspacey** [comment]
You're right. That's exactly what happened. My Mistake. It's fixed.
