### ISSUE TITLE
Mocking and storybook

### ISSUE THREAD

**Issue by vukk** [faceyspacey/redux-first-router-link#30]
I'm using storybook <https://github.com/storybooks/storybook> to develop common reusable "dumb" components shared between different applications the company has. Some of components combine other other components and use `<Link>` elements. A typical case is `<Link><Button /></Link>`, with the link parametrized from outside e.g. `<Link to={params.linkTo}>`.

redux-first-router of course assumes redux to store to exist and routes to be configured, which it does in our applications, but not in the storybook. Hence the following error message is displayed
```
Could not find "store" in either the context or props of "Connect(Link)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Link)".
```

I was wondering if there is a smart way to mock the store and redux-first-router existence, so that redux-first-router-link could be used in components while developing in the storybook?

The best outcome of the mocking would be that the links actually become no-op.

**Comment by vukk** [comment]
I tried aliasing in storybook, but it seems to be that extending it's webpack config to add resolve aliases currently breaks at least SVG support. I think it has to do with using create-react-app in order to not manage my webpack configs.

That's not a problem with redux-first-router-link though, so feel free to close this issue. That is unless you want it as a reminder to think about mocking :)

A hacky initial idea could be setting something in the React context that would tell the Link component to become a complete dummy one that doesn't even try to look for the redux store. I don't know how easy and/or (un)desirable this would be.

**Comment by faceyspacey** [comment]
Cool, I have a testing strategy coming up specifically for React Storybook, so I'll take a mental note and revisit this then. Thanks for taking the time to report back.
