### ISSUE TITLE
Add support for custom tagNames

### ISSUE THREAD

**Issue by swernerx** [faceyspacey/redux-first-router-link#34]
I currently have the need to make a full content cell clickable and linkable. As HTML does not allow for HTML tags around block level elements it would be useful to offer a non SEO-compliant version which does not set a `href` and is not based on a `a` tag. This in itself should not be super hard and would be a good match for a general link solution I think.

```html
<Link tagName="div">
  ...content
</Link>
```

**Comment by swernerx** [comment]
I am not so deep into flow (effectively never used it to assign any types). Without this I would just do a PR :)

**Comment by faceyspacey** [comment]
it might be time to learn Flow :). im stacked to the brim full of todos. Flow's necessary these days.

it is a good idea.

**Comment by swernerx** [comment]
would such a PR okay for you? Then I would try my best :)

**Comment by faceyspacey** [comment]
Yea it will work as long as everything else works the same. Ie only new props. NavLink should be updated to

**Comment by swernerx** [comment]
I'll check that.
