### ISSUE TITLE
Support for relative links?

### ISSUE THREAD

**Issue by raRaRa** [faceyspacey/redux-first-router-link#60]
Hey, first of all I want to thank you for RFR and RFRL. Made SSR plus more so much easier to work with :+1: 

I have one question regarding relative links in RFRL.

To give some context to the question I have these routes defined:

```
:lang?/subpage
:lang?
```

So when I'm on /de I want to be able to click on a link that has a relative link to subpage, e.g.

`<Link to={'subpage'} />`

But that doesn't seem to work. RFRL doesn't seem to match the link to any route. The expected behavior is that the route `/de/subpage` would match.

So I currently have to do:
`<Link to={{ type: 'SUBPAGE', payload: { lang: props.language } }}>`

But please note I really like that link structure, but the part I don't like is exposing the language prop to every component that links to a subpage. With a relative link I wouldn't need to know anything about language.

Is this something that is already possible with RFRL, and if not, would it be hard to implement? I assume it could look at the current URL and add the relative link on top of that.

Thanks!

**Comment by faceyspacey** [comment]
Glad u like it.

Check the top of the RFR repo. There is a new basename option which will do the trick for this use case. If u want to be able to change languages in the middle id need to add a changeBaseName function, which is something that may be possible. Until then u can just reload the page to a new URL with the correct basename and then the store would be reconfigured to use it. 

So if u did this u would never have to enter the language as a basename. 

As far as getting it as a param, for now u can store it in ur own reducer state and get it from thunks. But I'm thinking about adding the basename to action.meta.location.basename and state.location.basename so u can access it without using thunks or ur own reducers.

**Comment by faceyspacey** [comment]
relative links are supported in the upcoming Rudy release and will be concatenated on the current path (obviously) before attempting to match a route:

https://github.com/faceyspacey/redux-first-router/commit/c9f5e6d6a13ef1edde046d223417005a0bd72c03

here's the relevant code from the new Link component:

```js
if (url.charAt(0) === '#') {
    url = `${currentPathname}${url}`
  }
  else if (url.charAt(0) !== '/') {
    url = resolvePathname(url, currentPathname)
  }
```
