### ISSUE TITLE
Support any action, not just action object. EG: a thunk?

### ISSUE THREAD

**Issue by stevemao** [faceyspacey/redux-first-router-link#68]
Do you think it would be a good idea to support any action?

EG:

```js
<Link to={this.props.myThunk}>FP</Link>
```

Reason is I can just pass any mapped action to `to` and I can write all my actions in a separate file. I use a lot of thunks since I want to access some `state` with `getState` in my actions.

Looks like it's easy to implement, if you change https://github.com/faceyspacey/redux-first-router-link/blob/rudy/src/handlePress.js#L47
to

```js
const isAction = (to: ?To) => typeof to !== 'string' && !Array.isArray(to)
```

It should just work. Obviously user should add relevant middleware. But if they write it this way they should already added it.

**Comment by faceyspacey** [comment]
Probably better to check directly for a function. I've never heard of anything else middleware exists for which you can dispatch it.

PR it.

Also, u may be interested in skipping Redux-Thunk middleware and using pathless routes in RFR, which are new and better. Check the top of the readme for more info. Basically u can have routes with no path and just a thunk option and then u just dispatch action objects, and the follow-up portion of the thunk is mapped in your routesMap.

**Comment by stevemao** [comment]
PR opened: https://github.com/faceyspacey/redux-first-router-link/pull/69
