### ISSUE TITLE
how to provide a empty value to `to`?

### ISSUE THREAD

**Issue by stevemao** [faceyspacey/redux-first-router-link#71]
A lot of times I don't have a `to` value in the beginning. EG: a search button and only when user typed something in the input, it starts to generate a link

```js
<Link to={this.props.search} >search</Link>
```

The button should open the current page in a new tab when input is empty and users middle click on it, or do nothing if they left click, which is working fine. However, my console is spammed with a lot of warnings. Looking at https://github.com/faceyspacey/redux-first-router-link/blob/rudy/src/toUrl.js in order to get a default value: `#` we have to see a warning. 

I think the followings shouldn't warn:

```js
<Link to={this.props.search || null} >search</Link>
```

or 

```js
<Link to={this.props.search || ''} >search</Link>
```

with `null` we must have purposely give it an empty value and we are expecting to get a default href `#`. an empty string `''` is a valid string type so it definitely shouldn't warn.

**Comment by faceyspacey** [comment]
hmm, I'm honestly not exactly sure. But I feel like a possible solution would be accepting `null` or `'#'` without displaying warnings could be a solution. I'm going to be getting back to the link package for some upgrades, which involve the other PRs here, so that would be a better time for me to fully commit to something here.

In the meantime you could block warnings by monkey patching `console.warn` to do nothing if it detects the message text you're trying to avoid.

That said, '`#'` could be a fine answer to not warn on if you want to PR that. I wanna say `null` too, but I'm just not sure if we want to give that special meaning. It's a small detail, but we gotta be protective of these packages as it could have possible unanticipated side-effects.

**Comment by stevemao** [comment]
I think we need a default (noop) for all three formats

for `string`, we could accept `'#'`

for `array`, we could accept `['#']`

for `action`, we could do something like

```js
import { NOOP } from 'redux-first-router'

{
    type: NOOP
}
```

the warning needs to change to

```js
'[redux-first-router-link] `to` prop must be a non-empty string, non-empty array or action object. You provided:',
```

**Comment by faceyspacey** [comment]
oh lord. def dont want a NOOP.  I'd be fine with just the first one. ..also if this is the case, perhaps `null` is the best option after all.

**Comment by stevemao** [comment]
> def dont want a NOOP.

Why is that? looks like using a default action type is a standard way of doing it. `null` isn't really a valid action object.

**Comment by stevemao** [comment]
I really like the idea of supplying an action object and I pretty much use it everywhere. I try to ignore the `string` and `array` options as much as I can. Also good for consistency.

**Comment by faceyspacey** [comment]
Regarding NOOP, it's important to keep the API surface small. This use case here is a rare use-case. This is the first I'm hearing about it being a problem. And it looks like we're just doing it to avoid warnings.

I also like the idea of action objects. That's the best way to do it. 

At the end of the day, having a link that doesn't do anything is a bit bizarre--shouldn't you be showing a disabled button instead.

Let's just do this: remove this warning:
https://github.com/faceyspacey/redux-first-router-link/blob/master/src/toUrl.js#L34

That's fine--just as regular links in the browser won't cause any issues if you don't provide an href. If you provide that PR I'll merge it.

**Comment by faceyspacey** [comment]
We'll also need to make sure `handlePress` exits early rather than causes any problems with `pathToAction`:

https://github.com/faceyspacey/redux-first-router-link/blob/master/src/handlePress.js#L41

**Comment by ml242** [comment]
I also thought I'd add an opinion for a NOOP. I have a functional app with the package but at times I would like to disable the href based on auth or ui state. The easiest thing to do would be a ternary to default to a '#' but that gets added onto the url I've already built which results in a 404. To get around this I'll have to build up a lot more boilerplate code to render a different link component which seems counterproductive.

**Comment by faceyspacey** [comment]
In the next major release this will be solved.
