### ISSUE TITLE
Correct way to add anchor links?

### ISSUE THREAD

**Issue by NicholasGWK** [faceyspacey/redux-first-router-link#82]
Hey, I'm trying to add in an anchor tag to an existing path, but it gets URL encoded by actionToPath from path-to-regexp and I can't seem to find a way to overwrite the default encoding behaviour. Is there a better way to do this with this module? Currently trying something like this:

```
<Link to={type: LOCATION.ROOT, payload: { anchor: '#faq'}}/>

// routConfig

{ 'root': { path: ':anchor?'}}
```

Tried using toPath in the routeconfig but that isn't passed directly into the toPath() function in actionToPath after the path is compiled.

**Comment by faceyspacey** [comment]
If it's not supposed to trigger a Redux action, and the link package can't parse it, it's probably best to just create a regular a tag.

**Comment by NicholasGWK** [comment]
Thanks for the quick response! The particular case we're looking at is we want to link to a different page within the SPA, but want the anchor tag respected. Basically it's an FAQ link in the footer which is displayed on every page, but the FAQ is just a section on the root page, not a separate page of its own.

**Comment by faceyspacey** [comment]
hash's will get full support in the next version. For now, the best option is probably a real link that does a refresh unfortunately. However, `history.push('/foo#hash')` may work. So you could create a simple `onClick` handler to your link that does `e.preventDefault()` and calls `history.push`. That said, using history directly will be removed when Rudy is released, but could be a way to achieve what you want now without having to do a refresh. I'm not sure if the hash will be respected at this very moment, but it might.

Another work around is a link to the FAQ in the footer without the hash, but put its value in a payload param, and on the mount of the primary component trigger a linking to the hash (either via `history.push` or perhaps `history.pushState({}, null, '/foo#hash')`. The latter should definitely solve it, but I think `history.push` will work. 

That's all I got. I'm closing this for now, but know I'm gonna incorporate your needs in an upcoming version.

**Comment by BrendanFDMoore** [comment]
This seems related to [Scroll Restoration](https://github.com/faceyspacey/redux-first-router/blob/master/docs/scroll-restoration.md), no? Would hooking up this enhancer allow hash links to work?

**Comment by mynameistechno** [comment]
Is there an official way to solve this yet? I.e. trigger a redux action along with a scroll to anchor
