### ISSUE TITLE
TypeError: _selectLocationState is not a function

### ISSUE THREAD

**Issue by adamlapczynski** [faceyspacey/redux-first-router-link#85]
I'm trying to use a `Link` in a Jest + Enzyme test, but any tests that use it error out with the following. Based on what I've provided, are you able to determine if I'm doing something wrong, or perhaps if it might be due to a bug?

```
TypeError: _selectLocationState is not a function

    at selectLocationState (node_modules/redux-first-router/dist/connectRoutes.js:600:10)
    at Link (node_modules/redux-first-router-link/dist/Link.js:68:60)
    ...
```

I'm currently using:
```
    "redux-first-router": "^0.0.16-next",
    "redux-first-router-link": "^1.4.2",
```

I have the following in my test to ensure a `Link` gets rendered based on some logic in the `LinkButton` component:
```
const href = 'foo';
const component = mount(
  <Provider store={store}>
    <ThemeProvider theme={Theme}>
      <LinkButton href={href}>
        Foo
      </LinkButton>
    </ThemeProvider>
  </Provider>
);

expect(component.find('Link')).toHaveLength(1);
```
`store` is a mock store that contains `{ location: {} }` at the top level, among other mock props.

Inside my `LinkButton` component, I have logic that determines whether to render a `Link` component, or a regular `<a>` tag, based on the value of the `href` prop. This is what's rendered with the version using `Link`:

```
<Link to={path}>
  <CustomStyedLinkButton {...rest}>
    {children}
  </CustomStyledLinkButton>
</Link>
```

note: `ThemeProvider` is for styled-components

**Comment by faceyspacey** [comment]
`connectRoutes` will have to be called, as during that call `_selectionLocationState` gets assigned. You can call `connectRoutes` even if you don't use the middleware/enhancer/reducer and `selectLocationState` will now be a function.

**Comment by adamlapczynski** [comment]
Ah, thank you!
