### ISSUE TITLE
SEO link doesn't use basename

### ISSUE THREAD

**Issue by florian-bd** [faceyspacey/redux-first-router-link#87]
````<Link to="/foo"/>```` with basename defined in history 
````
const history = createHistory({
        basename: '/test'
    });
````
It redirects correctly to /test/foo but the HTML link points to http://localhost/foo instead of http://localhost/test/foo

**Comment by faceyspacey** [comment]
make sure you're using the latest @rudy tag on NPM for both the link + primary RFR package.

**Comment by epalace510** [comment]
@faceyspacey Is there a reason you aren't publishing to `latest` or that the `rudy` tags aren't following the same semver that you are using for latest? I also got this bug because I just grabbed `latest` out of npm, and I'd rather not put what feels like a devo branch into my package.json.

**Comment by faceyspacey** [comment]
use @rudy tag. It's not a devo branch. It's the best RFR 1 will ever be. Soon everything will come out as Rudy, and that's all I've had time to focus on.

**Comment by epalace510** [comment]
Thanks for the fast response! I'll make the switch, then.
