### ISSUE TITLE
A link from a page with a hash to a page without a hash doesn't update the URL bar

### ISSUE THREAD

**Issue by edahlseng** [faceyspacey/redux-first-router-link#89]
If I'm on a URL with a hash (say, `/store/fruits/apple#pricing`) and I click a link that points to a route without a tab (example shown below), clicking that link will correctly fire the redux action, but it won't update the URL bar.

```javascript
const routesMap = {
    FRUIT_NO_TAB: '/store/fruit/:fruitName'
}
```
```html
<NavLink to={{type: 'FRUIT_NO_TAB', payload: {fruitName: 'apple'}} activeClassName="active">Top of page</NavLink> 
```

**Comment by faceyspacey** [comment]
coming in Rudy. a few more weeks out.
