### ISSUE TITLE
Attempting to open a link in a new tab using middle mouse button does not work in Firefox

### ISSUE THREAD

**Issue by UberMouse** [faceyspacey/redux-first-router-link#94]
In the latest version of Firefox as of writing (59.0.2) attempting to middle mouse click a `<Link>` to open the link in a new tab does nothing. In Chrome this correctly opens the link in a new tab. 

The problem seems to stem from different behavior around running the onClick handler between Firefox and Chrome, in Chrome the handlePress.js function is not executed for a middle mouse click but it is for Firefox.

In Firefox this results in the default action of the click event being prevented which results in the action doing nothing. I've created a PR (#93) with a fix I've done locally that fixes it, I've only tested it in latest Firefox and Chrome, however.

**Comment by UberMouse** [comment]
bump @faceyspacey

**Comment by ScriptedAlchemy** [comment]
sorry for such delays here
im picking up this project and will start releasing updates and patches, just as with RFR2
